
package Partida;

import Historial.Historial;
import Juego.Jugador;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    
    private Historial historial;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        historial = new Historial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        partidaBoton = new javax.swing.JButton();
        ficheroBoton = new javax.swing.JButton();
        clasificacionBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("                        POKER JAVA");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        partidaBoton.setText("Nueva partida");
        partidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partidaBotonActionPerformed(evt);
            }
        });

        ficheroBoton.setText("Cargar fichero");
        ficheroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheroBotonActionPerformed(evt);
            }
        });

        clasificacionBoton.setText("Clasificacion");
        clasificacionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacionBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partidaBoton)
                    .addComponent(ficheroBoton)
                    .addComponent(clasificacionBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(partidaBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ficheroBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clasificacionBoton)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ficheroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheroBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ficheroBotonActionPerformed

    private void partidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partidaBotonActionPerformed
        String nombre = JOptionPane.showInputDialog("Introduzca su nombre:");
        if(historial.existeJugador(nombre)){
            JOptionPane.showMessageDialog(null,"El jugador ya existe!");
        }else{
            Jugador j = new Jugador(nombre);
            historial.crearJugador(nombre);
            String juego = (String) JOptionPane.showInputDialog(this, "¿A qué juego quieres jugar?", "Elegir Juego", 
                    JOptionPane.QUESTION_MESSAGE, null, new String[]{"Poker Texas Holdem", "Poker Clasico"}, "Poker Texas Holdem");
            if(juego!=null){
                switch(juego){
                    case "Poker Texas Holdem":
                        PartidaHoldem partidaH = new PartidaHoldem(j);
                        partidaH.setVisible(true);
                        break;
                    case "Poker Clasico":
                        //PartidaClassic partidaC = new PartidaClassic(j);
                        //partidaC.setVisible(true);
                        break;
                }
            }
        }
        
    }//GEN-LAST:event_partidaBotonActionPerformed

    private void clasificacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacionBotonActionPerformed
        Clasificacion clasifi = new Clasificacion(historial);
        clasifi.setVisible(true);
    }//GEN-LAST:event_clasificacionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clasificacionBoton;
    private javax.swing.JButton ficheroBoton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton partidaBoton;
    // End of variables declaration//GEN-END:variables
}
